---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: harbor
  releaseName: harbor
  values:
    metrics:
      enabled: true
