---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx-system
spec:
  interval: 1h
  chart:
    spec:
      chart: nginx
      version: 1.7.3
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: nginx-system
  releaseName: nginx
  values:
    controller:
      setAsDefaultIngress: true
      enableLatencyMetrics: true
    prometheus:
      create: true
