apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/kaitoii11/myapp/myapp-cb826f2bc9d05cb0325792ef047b7d72:sha256-8680a05483bfa8f2d0779176155b6cd7b2b95261033e90d873a5f7c7bc9ac963.sbom
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 9360
              protocol: TCP
          resources:
            limits:
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
