apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp
  namespace: myapp
  labels:
    team: myapp
spec:
  namespaceSelector:
    matchNames:
      - myapp
  selector:
    matchLabels:
      app: myapp
  endpoints:
  - port: metrics
    path: /metrics
