---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 15.3.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: traefik-system
  releaseName: traefik
  values:
    ingressClass:
      enabled: true
      isDefaultClass: false
    ports:
      traefik:
        expose: true
      metrics:
        expose: true
