---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: traefik-system
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://flagger.app
      chart: flagger
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: traefik-system
  releaseName: flagger
  values:
    prometheus:
      install: true
    meshProvider: traefik
