---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus-system
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 39.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: prometheus-system
  releaseName: prometheus
  values:
    global:
      rbac:
        pspEnabled: false
    prometheus:
      prometheusSpec:
        # Disable in order to match servicemonitor created from other helm charts
        serviceMonitorSelectorNilUsesHelmValues: false
        # Disable in order to match rule created from other helm charts
        ruleSelectorNilUsesHelmValues: false
        # Disable in order to match podmonitor created from other helm charts
        podMonitorSelectorNilUsesHelmValues: false
    grafana:
      service:
        type: LoadBalancer
      sidecar:
        dashboards:
          searchNamespace: ALL
