apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
configMapGenerator:
  - name: grafana-custom-dashboards
    namespace: prometheus-system
    files:
      - dashboards/cilium-metrics.json
      - dashboards/cilium-operator.json
      - dashboards/hubble.json
    options:
      labels:
        grafana_dashboard: "1"
