apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - ./rules
configMapGenerator:
  - name: cilium-dashboards
    namespace: prometheus-system
    files:
      - dashboards/cilium-metrics.json
      - dashboards/cilium-operator.json
      - dashboards/hubble.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: longhorn-dashboards
    namespace: prometheus-system
    files:
      - dashboards/longhorn.json
    options:
      labels:
        grafana_dashboard: "1"
