---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: fluent
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://fluent.github.io/helm-charts
      chart: fluentbit
      version: v3.1.6
      sourceRef:
        kind: HelmRepository
        name: fluentbit
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: fluent
  releaseName: fluent-bit
  values:
    kind: DaemonSet
    rbac:
      eventsAccess: true
    flush: 1
    metricsPort: 2020
    logLevel: info
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
    config:
      service: |
        [SERVICE]
            Daemon Off
            Flush {{ .Values.flush }}
            Log_Level {{ .Values.logLevel }}
            Parsers_File /fluent-bit/etc/parsers.conf
            Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port {{ .Values.metricsPort }}
            Health_Check On
      inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            multiline.parser docker, cri
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On
        [INPUT]
            Name systemd
            Tag host.*
            Systemd_Filter _SYSTEMD_UNIT=kubelet.service
            Read_From_Tail On
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
      outputs: |
        [OUTPUT]
            Name stdout
            Match *

