---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy
  namespace: trivy-system
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://aquasecurity.github.io/helm-charts/
      chart: trivy-operator
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: trivy-system
  releaseName: trivy
  values:
    trivy:
      ignoreUnfixed: true
