---

name: Schedule - Renovate Helm Release

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */12 * * *'

jobs:
  renovate-helm-releases:
    runs-on: ubuntu-20.04
    steps:
    - uses:  actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1


    - uses: k8s-at-home/renovate-helm-releases@v1
      with:
        # Path to the folder containing your Flux2 Helm Repositories and Helm Releases
        cluster-path: './mycluster'
        # Turn on debug logging
        debug: 'no'
        # Do not alter Helm Release files
        dry-run: 'no'

    - name: Create pull request for renovatebot helm-release
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: renovate-annotations
        delete-branch: true
        title: "update renovate annotations"
        signoff: true
        committer: "Kaito Ii <kaitoii1111@gmail.com>"
        author: "Kaito Ii <kaitoii1111@gmail.com>"
        assignees: "kaitoii11"
        commit-message: "update renovate annotations"
        body: |
          Update HelmReleases inorder for Renovate to pick up new versions of Helm charts
        labels: renovate/annotations
